### ISSUE TITLE
Probable error in Sphere::intersects

### ISSUE THREAD

**Issue by rohan166** [rohan166/raytracer#1]
After hardcoding a Sphere prop in the image creation logic, there is not a single intersection found. 
The prop is added in the middle of the screen so should be fairly visible.

Possible problems: 
- No light source
- Error in intersect logic

**Comment by andrewbuss** [comment]
Please file a JIRA

**Comment by lxbrtsch** [comment]
Or, uh, MIN?

`MIN(5, 2) + 5` will return 5.

**Comment by lxbrtsch** [comment]
https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Macro_Names

**Comment by rohan166** [comment]
pls

**Comment by andrewbuss** [comment]
fixed in https://github.com/rohan166/raytracer/commit/ed1684ffbcb8980e4274e26959ee49c500613bf3
